### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ArashPartow** [openhat-org/OpenHAT#1]
On the following line, there is a mention of a memory leak:

https://github.com/leomeyer/OpenHAT/blob/master/src/openhatd/openhatd/ExpressionPort.cpp#L76

Could you further elaborate as to where the leak is coming from _(is it ExprTk?)_  and what conditions enable the leak?

**Comment by leomeyer** [comment]
Hi,

thanks for getting in touch and, foremost, for providing your marvelous
expression library.

Perhaps I am just using it wrong, as I had to figure this out mostly by
myself.
What I'm trying to do is to get a list of unresolved variables and replace
those with the current runtime values of the corresponding objects. This
code runs in a relatively tight loop.

The issues I have are: 1. when I call symbol_table.add_constants() in my
loop I see increasing memory consumption, and 2. the constants pi, epsilon
and infinity are not treated as such while resolving; instead, the parser
seems to treat those as unresolved variables as well, so for my purposes
they are basically useless (but again, I may just be using it wrong).

My idea is that symbol_table.clear() should clear all objects which it
somehow perhaps doesn't seem to do for constants (?)
Also, setting parser.dec().collect_variables() = true should not collect
already registered constants as variables.

It's not a big issue for me, but if you want to test it please see the
attached test code below. Tested on 64 bit Windows 7 with Visual Studio
2015 Community Edition (create a Windows console application project).
Compiler settings should include the define _SCL_SECURE_NO_WARNINGS and
"/bigobj" as extra command line flag.

As an additional idea, perhaps it might be possible to have a function that
replaces the values of registered variables in the symbol table. Thus,
instead of clearing the table and re-adding everything I could just replace
the values with the current ones which would probably perform better.

If you have any questions please get back to me.

Thanks and regards
Leo


#include "stdafx.h"
#include <iostream>

#include "exprtk.hpp"

// #define MEMORY_LEAK 1

int main()
{
// variables that can be used
double a = 1.0, b = 2.0;

#ifdef MEMORY_LEAK
// constants are available, use "pi" to test
std::string expressionStr = "a + b + pi";
#else
std::string expressionStr = "a + b";
#endif

typedef exprtk::symbol_table<double> symbol_table_t;
typedef exprtk::expression<double> expression_t;
typedef exprtk::parser<double> parser_t;
typedef parser_t::dependent_entity_collector::symbol_t symbol_t;

symbol_table_t symbol_table;
expression_t expression;
std::deque<symbol_t> symbol_list;
parser_t parser;

expression.register_symbol_table(symbol_table);

// phase 1: find variables to resolve
symbol_table.clear();

// Adding constants leads to a memory leak; furthermore, constants are not
detected as known symbols.
#ifdef MEMORY_LEAK
symbol_table.add_constants();
#endif

// collect only variables as symbol names
parser.enable_unknown_symbol_resolver();
parser.dec().collect_variables() = true;

// compile to detect variables
if (!parser.compile(expressionStr, expression)) {
std::cout << ": Error in expression: " << parser.error() << std::endl;
return 1;
}

// store symbol list (input variables)
symbol_list.clear();
parser.dec().symbols(symbol_list);

parser.disable_unknown_symbol_resolver();
parser.dec().collect_variables() = false;

while (true) {

// phase 2: add found variables to the symbol table
symbol_table.clear();

#ifdef MEMORY_LEAK
symbol_table.add_constants();
#endif

for (std::size_t i = 0; i < symbol_list.size(); ++i)
{
symbol_t& symbol = symbol_list[i];

if (symbol.second != parser_t::e_st_variable)
continue;

if (symbol.first == "a") {
if (!symbol_table.add_variable(symbol.first, a))
return 1;
}
else
if (symbol.first == "b") {
if (!symbol_table.add_variable(symbol.first, b))
return 1;
}
// constants are somehow resolved as unknown variables, even though they
have been added
else if (symbol.first != "pi") {
std::cout << "Expression variable did not resolve to an available variable:
" << symbol.first << std::endl;
return 1;
}
}

// all unresolved variables have been added, compile again
if (!parser.compile(expressionStr, expression))
return 1;

std::cout << "Expression result: " << expression.value() << std::endl;
}
}



2016-11-25 11:34 GMT+01:00 Arash Partow <notifications@github.com>:

**Comment by ArashPartow** [comment]
@leomeyer  

> thanks for getting in touch and, foremost, for providing your marvelous expression library.

Thank-you!  :)

-------

From the above example, I believe what you're trying to do is:

0. There is a _predetermined set_ of variables in the system (eg: a, b, c, x, y and z)
1. Take as input an expression in string form
2. Determine which of the 'variables' in the **_predetermined set_** are used in the expression using a _throw-away_ compile pass
3. Bootstrap a 'clean' symbol_table with the variables detected/determined in the expression from **Step 2**
4. Finally compile the expression with the newly instantiated symbol_table
5. Evaluate the compiled expression at some later point

Is this correct?


In any case I can see where the problem may be. I'll be investigating the above mentioned leak, and get back to you soon when I have some more information.

**Comment by leomeyer** [comment]
I think that's correct, yes.

I'm not quite sure whether the term "predetermined set" has any further implications to you, but I think that fits the description. In my words: There's a set of labeled objects that represent numeric values. I want to provide an expression at system startup that refers to these values using their labels (or IDs). This expression does not change afterwards.

During normal operation the expression is continuously being evaluated. Just before the expression is to be evaluated the current values of the referenced objects need to be retrieved (by calling a method, I can't just provide pointers or references to internal variables). The expression is then being evaluated taking the current state of the system into account and yields the calculated value.

I currently do not need variables that are local to the expression (or script). Instead I assume that all unresolved variables refer to objects in my system. If such a need arises I'd have to find a workaround.

I don't want to provide all possible values up front before each and every evaluation, because the objects might be numerous and retrieving their values might be expensive, so I'd prefer to do only the necessary work. Also, some objects might signal an error state on value retrieval in which case the expression is not evaluated but is assumed to yield some kind of fallback value. This, of course, affects only the objects that are actually used in the expression.

Other expression libraries I've been using provide callback mechanisms (function pointers, lambdas...) that can be used to fill in the runtime values of unresolved variables. It took me quite some time to figure out how to do this with ExprTk, and I don't know whether I'm using it correctly (probably not); maybe you can guide me how to do this more efficiently.

**Comment by ArashPartow** [comment]
@leomeyer:  Initially, you did definitely find a memory leak. The leak was caused when .clear() was called on the symbol_table, all the internal components were being cleared except for the components holding the various constants (pi, inf etc). That issue has now been fixed with the latest revision.

-----------

> Other expression libraries I've been using provide callback mechanisms (function pointers, lambdas...) that can be used to fill in the runtime values of unresolved variables. It took me quite some time to figure out how to do this with ExprTk, and I don't know whether I'm using it correctly (probably not); maybe you can guide me how to do this more efficiently.

This functionality was already available, but wasn't well documented. I've updated the documentation to describe the various strategies one can use to handle "unknown symbols"

**Documentation (Unknown unknowns)**
https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L2328

**Examples**
https://github.com/ArashPartow/exprtk/blob/master/exprtk_test.cpp#L7606

Based on the example above, I added two helper functions to make solving the issue of determining what symbols are being used in a given string representation of an expression easier:

**collect_variables**
https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L3199

**collect_functions**
https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L32176

Also if you plan on having numerous expressions in your system that will consume/share common variables globally etc, do have a read of the following section:
https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L2152

----------

I think the above should resolve the issues you've encountered. If not do let me know.

**Comment by leomeyer** [comment]
Hi,
thank you very much for your feedback and the improvements.
I hope I will find time to integrate the changes soon.

Regards, Leo

2016-12-15 1:13 GMT+01:00 Arash Partow <notifications@github.com>:
